################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CREF := 
SRC_DEPS := 
OBJCOPY := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
OBJS := 
SX_UPPER_DEPS := 
ASM_DEPS := 
MAP := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/board/cpkcor_ra8d1 \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_adc \
ra/fsp/src/r_ceu \
ra/fsp/src/r_dmac \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_ioport \
ra/fsp/src/r_rtc \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/r_sdhi \
ra/fsp/src/rm_freertos_port \
ra_gen \
src/CEU \
src/DISPLAY \
src/FILE \
src/GUI \
src/GUI/guider_customer_fonts \
src/GUI/lvgl-9.2.1/demos/benchmark/assets \
src/GUI/lvgl-9.2.1/demos/benchmark \
src/GUI/lvgl-9.2.1/demos/flex_layout \
src/GUI/lvgl-9.2.1/demos/keypad_encoder \
src/GUI/lvgl-9.2.1/demos \
src/GUI/lvgl-9.2.1/demos/multilang/assets/avatars \
src/GUI/lvgl-9.2.1/demos/multilang/assets/emojis \
src/GUI/lvgl-9.2.1/demos/multilang/assets/fonts \
src/GUI/lvgl-9.2.1/demos/multilang/assets \
src/GUI/lvgl-9.2.1/demos/multilang \
src/GUI/lvgl-9.2.1/demos/music/assets \
src/GUI/lvgl-9.2.1/demos/music \
src/GUI/lvgl-9.2.1/demos/render/assets \
src/GUI/lvgl-9.2.1/demos/render \
src/GUI/lvgl-9.2.1/demos/scroll \
src/GUI/lvgl-9.2.1/demos/stress \
src/GUI/lvgl-9.2.1/demos/transform/assets \
src/GUI/lvgl-9.2.1/demos/transform \
src/GUI/lvgl-9.2.1/demos/vector_graphic/assets \
src/GUI/lvgl-9.2.1/demos/vector_graphic \
src/GUI/lvgl-9.2.1/demos/widgets/assets \
src/GUI/lvgl-9.2.1/demos/widgets \
src/GUI/lvgl-9.2.1/examples/anim \
src/GUI/lvgl-9.2.1/examples/assets \
src/GUI/lvgl-9.2.1/examples/assets/emoji \
src/GUI/lvgl-9.2.1/examples/event \
src/GUI/lvgl-9.2.1/examples/get_started \
src/GUI/lvgl-9.2.1/examples/layouts/flex \
src/GUI/lvgl-9.2.1/examples/layouts/grid \
src/GUI/lvgl-9.2.1/examples/libs/barcode \
src/GUI/lvgl-9.2.1/examples/libs/bmp \
src/GUI/lvgl-9.2.1/examples/libs/ffmpeg \
src/GUI/lvgl-9.2.1/examples/libs/freetype \
src/GUI/lvgl-9.2.1/examples/libs/gif \
src/GUI/lvgl-9.2.1/examples/libs/libjpeg_turbo \
src/GUI/lvgl-9.2.1/examples/libs/libpng \
src/GUI/lvgl-9.2.1/examples/libs/lodepng \
src/GUI/lvgl-9.2.1/examples/libs/qrcode \
src/GUI/lvgl-9.2.1/examples/libs/rlottie \
src/GUI/lvgl-9.2.1/examples/libs/tiny_ttf \
src/GUI/lvgl-9.2.1/examples/libs/tjpgd \
src/GUI/lvgl-9.2.1/examples/others/file_explorer \
src/GUI/lvgl-9.2.1/examples/others/fragment \
src/GUI/lvgl-9.2.1/examples/others/gridnav \
src/GUI/lvgl-9.2.1/examples/others/ime \
src/GUI/lvgl-9.2.1/examples/others/imgfont \
src/GUI/lvgl-9.2.1/examples/others/monkey \
src/GUI/lvgl-9.2.1/examples/others/observer \
src/GUI/lvgl-9.2.1/examples/others/snapshot \
src/GUI/lvgl-9.2.1/examples/porting \
src/GUI/lvgl-9.2.1/examples/porting/osal \
src/GUI/lvgl-9.2.1/examples/scroll \
src/GUI/lvgl-9.2.1/examples/styles \
src/GUI/lvgl-9.2.1/examples/widgets/animimg \
src/GUI/lvgl-9.2.1/examples/widgets/arc \
src/GUI/lvgl-9.2.1/examples/widgets/bar \
src/GUI/lvgl-9.2.1/examples/widgets/button \
src/GUI/lvgl-9.2.1/examples/widgets/buttonmatrix \
src/GUI/lvgl-9.2.1/examples/widgets/calendar \
src/GUI/lvgl-9.2.1/examples/widgets/canvas \
src/GUI/lvgl-9.2.1/examples/widgets/chart \
src/GUI/lvgl-9.2.1/examples/widgets/checkbox \
src/GUI/lvgl-9.2.1/examples/widgets/dropdown \
src/GUI/lvgl-9.2.1/examples/widgets/image \
src/GUI/lvgl-9.2.1/examples/widgets/imagebutton \
src/GUI/lvgl-9.2.1/examples/widgets/keyboard \
src/GUI/lvgl-9.2.1/examples/widgets/label \
src/GUI/lvgl-9.2.1/examples/widgets/led \
src/GUI/lvgl-9.2.1/examples/widgets/line \
src/GUI/lvgl-9.2.1/examples/widgets/list \
src/GUI/lvgl-9.2.1/examples/widgets/lottie \
src/GUI/lvgl-9.2.1/examples/widgets/menu \
src/GUI/lvgl-9.2.1/examples/widgets/msgbox \
src/GUI/lvgl-9.2.1/examples/widgets/obj \
src/GUI/lvgl-9.2.1/examples/widgets/roller \
src/GUI/lvgl-9.2.1/examples/widgets/scale \
src/GUI/lvgl-9.2.1/examples/widgets/slider \
src/GUI/lvgl-9.2.1/examples/widgets/span \
src/GUI/lvgl-9.2.1/examples/widgets/spinbox \
src/GUI/lvgl-9.2.1/examples/widgets/spinner \
src/GUI/lvgl-9.2.1/examples/widgets/switch \
src/GUI/lvgl-9.2.1/examples/widgets/table \
src/GUI/lvgl-9.2.1/examples/widgets/tabview \
src/GUI/lvgl-9.2.1/examples/widgets/textarea \
src/GUI/lvgl-9.2.1/examples/widgets/tileview \
src/GUI/lvgl-9.2.1/examples/widgets/win \
src/GUI/lvgl-9.2.1/src/core \
src/GUI/lvgl-9.2.1/src/display \
src/GUI/lvgl-9.2.1/src/draw \
src/GUI/lvgl-9.2.1/src/draw/nxp/pxp \
src/GUI/lvgl-9.2.1/src/draw/nxp/vglite \
src/GUI/lvgl-9.2.1/src/draw/renesas/dave2d \
src/GUI/lvgl-9.2.1/src/draw/sdl \
src/GUI/lvgl-9.2.1/src/draw/sw/blend/helium \
src/GUI/lvgl-9.2.1/src/draw/sw/blend \
src/GUI/lvgl-9.2.1/src/draw/sw/blend/neon \
src/GUI/lvgl-9.2.1/src/draw/sw \
src/GUI/lvgl-9.2.1/src/draw/vg_lite \
src/GUI/lvgl-9.2.1/src/drivers/display/drm \
src/GUI/lvgl-9.2.1/src/drivers/display/fb \
src/GUI/lvgl-9.2.1/src/drivers/display/ili9341 \
src/GUI/lvgl-9.2.1/src/drivers/display/lcd \
src/GUI/lvgl-9.2.1/src/drivers/display/renesas_glcdc \
src/GUI/lvgl-9.2.1/src/drivers/display/st7735 \
src/GUI/lvgl-9.2.1/src/drivers/display/st7789 \
src/GUI/lvgl-9.2.1/src/drivers/display/st7796 \
src/GUI/lvgl-9.2.1/src/drivers/evdev \
src/GUI/lvgl-9.2.1/src/drivers/glfw \
src/GUI/lvgl-9.2.1/src/drivers/libinput \
src/GUI/lvgl-9.2.1/src/drivers/nuttx \
src/GUI/lvgl-9.2.1/src/drivers/qnx \
src/GUI/lvgl-9.2.1/src/drivers/sdl \
src/GUI/lvgl-9.2.1/src/drivers/wayland \
src/GUI/lvgl-9.2.1/src/drivers/windows \
src/GUI/lvgl-9.2.1/src/drivers/x11 \
src/GUI/lvgl-9.2.1/src/font \
src/GUI/lvgl-9.2.1/src/indev \
src/GUI/lvgl-9.2.1/src/layouts/flex \
src/GUI/lvgl-9.2.1/src/layouts/grid \
src/GUI/lvgl-9.2.1/src/layouts \
src/GUI/lvgl-9.2.1/src/libs/barcode \
src/GUI/lvgl-9.2.1/src/libs/bin_decoder \
src/GUI/lvgl-9.2.1/src/libs/bmp \
src/GUI/lvgl-9.2.1/src/libs/ffmpeg \
src/GUI/lvgl-9.2.1/src/libs/freetype \
src/GUI/lvgl-9.2.1/src/libs/fsdrv \
src/GUI/lvgl-9.2.1/src/libs/gif \
src/GUI/lvgl-9.2.1/src/libs/libjpeg_turbo \
src/GUI/lvgl-9.2.1/src/libs/libpng \
src/GUI/lvgl-9.2.1/src/libs/lodepng \
src/GUI/lvgl-9.2.1/src/libs/lz4 \
src/GUI/lvgl-9.2.1/src/libs/qrcode \
src/GUI/lvgl-9.2.1/src/libs/rle \
src/GUI/lvgl-9.2.1/src/libs/rlottie \
src/GUI/lvgl-9.2.1/src/libs/tiny_ttf \
src/GUI/lvgl-9.2.1/src/libs/tjpgd \
src/GUI/lvgl-9.2.1/src \
src/GUI/lvgl-9.2.1/src/misc/cache \
src/GUI/lvgl-9.2.1/src/misc \
src/GUI/lvgl-9.2.1/src/osal \
src/GUI/lvgl-9.2.1/src/others/file_explorer \
src/GUI/lvgl-9.2.1/src/others/fragment \
src/GUI/lvgl-9.2.1/src/others/gridnav \
src/GUI/lvgl-9.2.1/src/others/ime \
src/GUI/lvgl-9.2.1/src/others/imgfont \
src/GUI/lvgl-9.2.1/src/others/monkey \
src/GUI/lvgl-9.2.1/src/others/observer \
src/GUI/lvgl-9.2.1/src/others/snapshot \
src/GUI/lvgl-9.2.1/src/others/sysmon \
src/GUI/lvgl-9.2.1/src/others/vg_lite_tvg \
src/GUI/lvgl-9.2.1/src/stdlib/builtin \
src/GUI/lvgl-9.2.1/src/stdlib/clib \
src/GUI/lvgl-9.2.1/src/stdlib \
src/GUI/lvgl-9.2.1/src/stdlib/micropython \
src/GUI/lvgl-9.2.1/src/stdlib/rtthread \
src/GUI/lvgl-9.2.1/src/themes/default \
src/GUI/lvgl-9.2.1/src/themes \
src/GUI/lvgl-9.2.1/src/themes/mono \
src/GUI/lvgl-9.2.1/src/themes/simple \
src/GUI/lvgl-9.2.1/src/tick \
src/GUI/lvgl-9.2.1/src/widgets/animimage \
src/GUI/lvgl-9.2.1/src/widgets/arc \
src/GUI/lvgl-9.2.1/src/widgets/bar \
src/GUI/lvgl-9.2.1/src/widgets/button \
src/GUI/lvgl-9.2.1/src/widgets/buttonmatrix \
src/GUI/lvgl-9.2.1/src/widgets/calendar \
src/GUI/lvgl-9.2.1/src/widgets/canvas \
src/GUI/lvgl-9.2.1/src/widgets/chart \
src/GUI/lvgl-9.2.1/src/widgets/checkbox \
src/GUI/lvgl-9.2.1/src/widgets/dropdown \
src/GUI/lvgl-9.2.1/src/widgets/image \
src/GUI/lvgl-9.2.1/src/widgets/imagebutton \
src/GUI/lvgl-9.2.1/src/widgets/keyboard \
src/GUI/lvgl-9.2.1/src/widgets/label \
src/GUI/lvgl-9.2.1/src/widgets/led \
src/GUI/lvgl-9.2.1/src/widgets/line \
src/GUI/lvgl-9.2.1/src/widgets/list \
src/GUI/lvgl-9.2.1/src/widgets/lottie \
src/GUI/lvgl-9.2.1/src/widgets/menu \
src/GUI/lvgl-9.2.1/src/widgets/msgbox \
src/GUI/lvgl-9.2.1/src/widgets/objx_templ \
src/GUI/lvgl-9.2.1/src/widgets/property \
src/GUI/lvgl-9.2.1/src/widgets/roller \
src/GUI/lvgl-9.2.1/src/widgets/scale \
src/GUI/lvgl-9.2.1/src/widgets/slider \
src/GUI/lvgl-9.2.1/src/widgets/span \
src/GUI/lvgl-9.2.1/src/widgets/spinbox \
src/GUI/lvgl-9.2.1/src/widgets/spinner \
src/GUI/lvgl-9.2.1/src/widgets/switch \
src/GUI/lvgl-9.2.1/src/widgets/table \
src/GUI/lvgl-9.2.1/src/widgets/tabview \
src/GUI/lvgl-9.2.1/src/widgets/textarea \
src/GUI/lvgl-9.2.1/src/widgets/tileview \
src/GUI/lvgl-9.2.1/src/widgets/win \
src \
src/HX711 \
src/KEY_BEEP_LED \
src/MAX17048 \
src/MAX6675 \
src/MQ4_MQ5 \
src/SDRAM \
src/SNR9816 \
src/WIFI \

